import type { JSONRendererTheme } from './Component';

export const JSON_RENDERER_THEMES = {
  default: {
    background: 'transparent',
    color: 'inherit',
    lineNumberBackground: 'grey',
    lineNumberColor: 'inherit',
    indentGuideColor: 'black',
    toggleBackground: 'white',
    toggleColor: 'inherit',
    toggleBorderColor: '#6e7781',
  },
  githubLight: {
    background: '#ffffff',
    color: '#24292f',
    lineNumberBackground: '#f6f8fa',
    lineNumberColor: '#57606a',
    indentGuideColor: '#d0d7de',
    toggleBackground: '#ffffff',
    toggleColor: '#24292f',
    toggleBorderColor: '#8c959f',
    keyColor: '#0550ae',
    stringColor: '#0a3069',
    numberColor: '#0550ae',
    booleanColor: '#cf222e',
    nullColor: '#8250df',
  },
  githubDark: {
    background: '#0d1117',
    color: '#c9d1d9',
    lineNumberBackground: '#161b22',
    lineNumberColor: '#8b949e',
    indentGuideColor: '#30363d',
    toggleBackground: '#161b22',
    toggleColor: '#c9d1d9',
    toggleBorderColor: '#30363d',
    keyColor: '#79c0ff',
    stringColor: '#a5d6ff',
    numberColor: '#79c0ff',
    booleanColor: '#ff7b72',
    nullColor: '#d2a8ff',
  },
  monokai: {
    background: '#272822',
    color: '#f8f8f2',
    lineNumberBackground: '#3e3d32',
    lineNumberColor: '#cfcfc2',
    indentGuideColor: '#75715e',
    toggleBackground: '#3e3d32',
    toggleColor: '#f8f8f2',
    toggleBorderColor: '#75715e',
    keyColor: '#a6e22e',
    stringColor: '#e6db74',
    numberColor: '#ae81ff',
    booleanColor: '#ae81ff',
    nullColor: '#f92672',
  },
} as const satisfies Record<string, JSONRendererTheme>;

export type JSONRendererThemeName = keyof typeof JSON_RENDERER_THEMES;
